config/routes.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Squash::Application.routes.draw do
  resources :projects, except: [:new] do
    member { patch :rekey }
    resources :commits do
      member { get :context }
    end
    resources :environments, only: [:update] do
      resources :bugs, except: [:new, :create, :edit] do
        collection { get :count }
        member { post :watch, :notify_deploy, :notify_occurrence }
        resources :occurrences, only: [:index, :show] do
          collection { get :count, :aggregate, :histogram }
        end
        resources :events, only: :index
        resources :comments, except: [:show, :new, :edit]
        resource :notification_threshold, only: [:create, :update, :destroy]
      end
    end
    resources :memberships, controller: 'project/memberships', only: [:index, :create, :update, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
    resource :membership, controller: 'project/membership', as: :my_membership, only: [:edit, :update, :destroy] do
      member { post :join }
      resources :emails, controller: 'emails', only: [:index, :create]
    end
  end

  constraints(id: /[^\/]+?/, format: 'html') do
    resources :users, only: :show
  end
  actions = [:index]
  actions << :create if Squash::Configuration.authentication.strategy == 'password'
  resources :users, only: actions

  actions = [:show]
  actions << :update if Squash::Configuration.authentication.strategy == 'password'
  resource :account, only: actions do
    resources :memberships, controller: 'account/memberships', only: [:index]
    resources :bugs, controller: 'account/bugs', only: :index
    resources :events, controller: 'account/events', only: :index
    resources :emails, controller: 'emails', only: [:index, :create, :destroy], constraints: {id: /[^\/]+?/, format: 'json'}
  end

  namespace :jira do
    resources :projects, only: :index
    resources :issues, only: :show
    resources :statuses, only: :index
  end unless Squash::Configuration.jira.disabled?

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'signup' => 'users#create' if Squash::Configuration.authentication.strategy == 'password'

  post 'api/1.0/notify' => 'api/v1#notify'
  post 'api/1.0/deploy' => 'api/v1#deploy'
  post 'api/1.0/symbolication' => 'api/v1#symbolication'
  post 'api/1.0/deobfuscation' => 'api/v1#deobfuscation'
  post 'api/1.0/sourcemap' => 'api/v1#sourcemap'

  get 'search/suggestions' => 'search#suggestions'
  get 'search' => 'search#search'

  root to: 'projects#index'

  if Squash::Configuration.concurrency.background_runner == 'Sidekiq'
    require 'sidekiq/web'
    constraints lambda { |request| SidekiqAuthConstraint.authorized?(request) } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/controllers/jira/projects_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that loads JIRA projects.

class Jira::ProjectsController < ApplicationController
  skip_before_filter :login_required
  respond_to :json

  # Returns a list of JIRA projects.
  #
  # * `GET /jira/projects`

  def index
    @projects = Service::JIRA.projects
    respond_with(@projects) do |format|
      format.json { render json: @projects.to_a.sort_by(&:name).map(&:attrs).to_json }
    end
  end
end

app/controllers/project/membership_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Singleton resource controller for working with the current {User}'s
# {Membership} in a {Project}.

class Project::MembershipController < ApplicationController
  before_filter :find_project
  before_filter :find_membership, except: :join
  before_filter :must_not_be_owner, only: :destroy

  respond_to :html, :json

  # Creates a new Membership linking this Project to the current User. The user
  # will have member privileges.
  #
  # Routes
  # ------
  #
  # * `POST /projects/:project_id/membership/join`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                                                       |
  # |:-------------|:----------------------------------------------------------------------|
  # | `project_id` | The Project's slug.                                                   |
  # | `next`       | For HTML requests, the URL to be taken to next (default project URL). |

  def join
    @membership = @project.memberships.where(user_id: current_user.id).find_or_create! { |m| m.user = current_user }
    respond_with @membership, location: project_url(@project)
  end

  # Displays a form where a User can modify their Membership settings.
  #
  # Routes
  # ------
  #
  # * `GET /projects/:project_id/membership/edit`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                     |
  # |:-------------|:--------------------|
  # | `project_id` | The Project's slug. |

  def edit
    respond_with @membership
  end

  # Updates a User's email settings for this Membership's Project.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/membership`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                     |
  # |:-------------|:--------------------|
  # | `project_id` | The Project's slug. |
  #
  # Body Parameters
  # ---------------
  #
  # |              |                                                        |
  # |:-------------|:-------------------------------------------------------|
  # | `membership` | Parameterized hash of new Membership attribute values. |

  def update
    @membership.update_attributes membership_params
    respond_with @membership, location: edit_project_my_membership_url(@project)
  end

  # Removes membership from a Project. A Project owner cannot leave his/her
  # Project without first reassigning ownership.
  #
  # Routes
  # ------
  #
  # * `DELETE /project/:project_id/membership`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                     |
  # |:-------------|:--------------------|
  # | `project_id` | The Project's slug. |
  #
  # Responses
  # ---------
  #
  # ### Deleting an owned project
  #
  # If the User attempts to delete a Project s/he owns, a 401 Unauthorized
  # status is returned with an empty response body.

  def destroy
    @membership.destroy
    respond_with @membership do |format|
      format.html { redirect_to account_url, flash: {success: t('controllers.project.membership.destroy.deleted', name: @membership.project.name)} }
    end
  end

  private

  def find_membership
    @membership = current_user.memberships.find_by_project_id!(@project.id)
  end

  def must_not_be_owner
    if @membership.role == :owner
      respond_to do |format|
        format.html { redirect_to account_url, alert: t('controllers.project.membership.must_not_be_owner') }
      end
      return false
    else
      return true
    end
  end

  def membership_params
    params.require(:membership).permit(:send_assignment_emails,
                                       :send_comment_emails,
                                       :send_resolution_emails)
  end
end

app/controllers/project/memberships_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller that works with {Membership Memberships} belonging to a {Project}.
#
# Common
# ======
#
# Path Parameters
# ---------------
#
# |              |                     |
# |:-------------|:--------------------|
# | `project_id` | The Project's slug. |

class Project::MembershipsController < ApplicationController
  before_filter :find_project
  before_filter :find_membership, only: [:update, :destroy]
  before_filter :admin_login_required, except: :index

  respond_to :json

  # Returns a list of the 10 most recently-created memberships to a project.
  #
  # Routes
  # ------
  #
  # * `GET /projects/:project_id/memberships.json`
  #
  # Query Parameters
  # ----------------
  #
  # |         |                                                                                                    |
  # |:--------|:---------------------------------------------------------------------------------------------------|
  # | `query` | If set, includes only those memberships where the username begins with `query` (case-insensitive). |

  def index
    respond_to do |format|
      format.json do
        @memberships = @project.memberships.order('created_at DESC').limit(10)
        @memberships = @memberships.user_prefix(params[:query]) if params[:query].present?

        render json: decorate(@memberships)
      end
    end
  end

  # Adds a user to this project.
  #
  # Routes
  # ------
  #
  # * `POST /projects/:project_id/memberships.json`
  #
  # Body Parameters
  # ---------------
  #
  # The body parameters can be JSON- or form URL-encoded.
  #
  # |              |                                          |
  # |:-------------|:-----------------------------------------|
  # | `membership` | Parameterized hash of Membership fields. |

  def create
    if params[:membership][:user_username]
      params[:membership][:user_id] = User.find_by_username(params[:membership].delete('user_username')).try!(:id)
    end

    @membership = @project.memberships.create(membership_params)
    respond_with @project, @membership
  end

  # Alters a user's membership to this project.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/memberships/:id.json`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                        |
  # |:-----|:-----------------------|
  # | `id` | The {User}'s username. |
  #
  # Body Parameters
  # ---------------
  #
  # The body parameters can be JSON- or form URL-encoded.
  #
  # |              |                                          |
  # |:-------------|:-----------------------------------------|
  # | `membership` | Parameterized hash of Membership fields. |

  def update
    @membership.update_attributes membership_params

    respond_with @project, @membership
  end

  # Removes a user from this project.
  #
  # Routes
  # ------
  #
  # * `DELETE /projects/:project_id/memberships/:id.json`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                      |
  # |:-----|:---------------------|
  # | `id` | The User's username. |

  def destroy
    if current_user.role(@project) == :admin && @membership.admin?
      return respond_to do |format|
        format.json { head :forbidden }
      end
    end

    @membership.destroy
    head :no_content
  end

  private

  def find_project
    @project = Project.find_from_slug!(params[:project_id])
  end

  def find_membership
    @membership = @project.memberships.find_by_user_id!(User.find_by_username!(params[:id]))
  end

  def decorate(memberships)
    memberships.map do |membership|
      membership.as_json(include: [:user, :project]).deep_merge(
          user:           membership.user.as_json.merge(url: user_url(membership.user), name: membership.user.name),
          created_string: l(membership.created_at, format: :short_date),
          human_role:     membership.human_role.capitalize,
          role:           membership.role
      )
    end
  end

  def membership_params
    params.require(:membership).permit(*(
        case current_user.role(@project)
          when :admin
            [:user_id]
          when :owner
            [:user_id, :admin]
        end
    ))
  end
end

app/views/projects/edit.js.erb
// Copyright 2014 Square Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

$(document).ready(function() {
  new MemberPanel($('#members'),
                  "<%= escape_javascript @project.name %>",
                  "<%= @project.to_param %>",
                  "<%= users_url %>",
                  "<%= project_memberships_url(@project, format: 'json') %>",
                  "<%= project_membership_url(@project, 'USERID', format: 'json') %>",
                  "<%= project_url(@project, format: 'json') %>",
                  "<%= current_user.role(@project).to_s %>",
                  false);

  $('#insert-prefab').click(function() {
    var lines;
    var prefabMenu = $('#prefab');

    switch(prefabMenu.val()) {
      case 'rails':
        lines = ["vendor/"];
        break;
      default: lines = [];
    }

    if (lines)
      $('#project_filter_paths_string').val(($('#project_filter_paths_string').val() + "\n" + lines.join("\n")).replace(/^\n/, ''));

    prefabMenu.val('');

    return false;
  });
});

app/views/projects/index.js.erb
// Copyright 2014 Square Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

$(document).ready(function() {
  new PageManager().setup();
});

function PageManager() {
  this.setup = function() {
    this.setupWatchedBugsTable();
    this.setupAssignedBugsTable();
    this.setupMyFeed();
    this.setupFindAnyProject();
  };

  this.setupFindAnyProject = function() {
    new DynamicSearchField($('#find-project'), this.processAnyProjectSearchResults);
    this.processAnyProjectSearchResults(''); // pre-populate with most recent projects
  };

  this.processAnyProjectSearchResults = function(query) {
    var self = this;
    $.ajax('<%= projects_url(format: 'json') %>?query=' + encodeURIComponent(query), {
      type:    'GET',
      success: function(results) {
        var resultList = $('#find-project-search-results');
        resultList.find('li').remove();
        $.each(results, function(_, project) {
          var li = $('<li/>').appendTo(resultList);
          var h5 = $('<h5/>').append($('<a/>').text(project.name).attr('href', project.url)).appendTo(li);

          if (project.role == null) {
            var btn = $("<button/>").text("Join").appendTo(h5);
            btn.click(function() {
              $.ajax(project.join_url, {
                type: 'POST',
                success: function() { self.processAnyProjectSearchResults(query); },
                error: function() { new Flash('alert').text("Couldn’t join project."); }
              });
            });
          }

          var p = $('<p/>').appendTo(li);
          switch (project.role) {
            case 'owner':
              $('<strong/>').text('Owner').appendTo(p);
              break;
            case 'admin':
              $('<strong/>').text('Administrator').appendTo(p);
              break;
            case 'member':
              $('<strong/>').text('Project member').appendTo(p);
              break;
            default:
              p.text("Owned by ");
              $('<a/>').text(project.owner.name).attr('href', project.owner.url).appendTo(p);
          }
          p.append(' — created ');
          $('<time/>').attr('datetime', project.created_at).appendTo(p).liveUpdate();
        });
      },
      error:   function() { new Flash('alert').text("Error retrieving search results."); }
    });
  };

  this.setupWatchedBugsTable = function() {
    var table = new SortableTable($('#watched-bugs'),
      "<%= account_bugs_url(format: 'json', type: 'watched') %>",
      [
        { key: 'project_and_environment', title: "Project", sortable: false, htmlGenerator: function(bug) {
          var span = $('<span/>').text(bug.environment.name);
          $('<br/>').prependTo(span);
          $('<strong/>').text(bug.project.name).prependTo(span);
          return span;
        } },
          { key: 'class_message', title: "Message", sortable: false, htmlGenerator: function(bug) {
            var sp = $('<span/>').addClass('long-words').text(bug.message_template);
            $('<br/>').prependTo(sp);
            $('<tt/>').text(bug.class_name).prependTo(sp);
            return sp;
          } },
        { title: "File", sortable: false, textGenerator: formatBugFile },
        { key: 'occurrences', title: "Counts", sortable: false, htmlGenerator: function(bug) {
          var sp = $('<span/>');
          sp.append(bug.occurrences_count);
          $('<i/>').addClass('fa fa-exclamation-circle').appendTo(sp);
          if (bug.comments_count > 0) {
            sp.append(' ' + bug.comments_count);
            $('<i/>').addClass('fa fa-comment').appendTo(sp);
          }
          return sp;
        } },
        { key: 'latest', title: "Latest", sortable: false, htmlGenerator: function(bug) {
          return $('<time/>').attr('datetime', bug.latest_occurrence).liveUpdate();
        } },
        { key: 'user_name', title: "Assigned To", sortable: false, textGenerator: function(bug) { return bug.assigned_user ? bug.assigned_user.name : "no one"; } },
        { key: 'unwatch', title: '', sortable: false, htmlGenerator: function(bug) {
          return $('<a/>').addClass('fa fa-star icon-large unwatch').attr('href', '#').click(function() {
            $.ajax(bug.watch_url, {
              type: 'POST',
              success: function() { table.refreshData(); },
              error: function() {
                new Flash('alert').text("Couldn’t unwatch that bug.");
                table.refreshData();
              },
              dataType: 'text'
            });
            return false;
          });
        } }
      ],
      {
        sort_key:    'latest',
        scroll_with: 'id'
      }
    ).refreshData();
  };

  this.setupAssignedBugsTable = function() {
      new SortableTable($('#assigned-bugs'),
                        "<%= account_bugs_url(format: 'json') %>",
                        [
                          { key: 'project_and_environment', title: "Project", sortable: false, htmlGenerator: function(bug) {
                            var span = $('<span/>').text(bug.environment.name);
                            $('<br/>').prependTo(span);
                            $('<strong/>').text(bug.project.name).prependTo(span);
                            return span;
                          } },
                          { key: 'class_message', title: "Message", sortable: false, htmlGenerator: function(bug) {
                            var sp = $('<span/>').addClass('long-words').text(bug.message_template);
                            $('<br/>').prependTo(sp);
                            $('<tt/>').text(bug.class_name).prependTo(sp);
                            return sp;
                          } },
                          { title: "File", sortable: false, textGenerator: formatBugFile },
                          { key: 'occurrences', title: "Counts", sortable: false, htmlGenerator: function(bug) {
                            var sp = $('<span/>');
                            sp.append(bug.occurrences_count);
                            $('<i/>').addClass('fa fa-exclamation-circle').appendTo(sp);
                            if (bug.comments_count > 0) {
                              sp.append(' ' + bug.comments_count);
                              $('<i/>').addClass('fa fa-comment').appendTo(sp);
                            }
                            return sp;
                          } },
                          { key: 'latest', title: "Latest", sortable: false, htmlGenerator: function(bug) {
                            return $('<time/>').attr('datetime', bug.latest_occurrence).liveUpdate();
                          } },
                          { key: 'status', title: "Status", sortable: false, textGenerator: function(bug) {
                            switch (bug.status) {
                              case 'open': case 'assigned': return "unresolved";
                              case 'fixed': return "fixed";
                              case 'fix_deployed': return "fix deployed";
                            }
                          } }
                        ],
                        {
                          sort_key:    'latest',
                          scroll_with: 'id'
                        }
      ).refreshData();
    };

  this.setupMyFeed = function() {
    new Feed("<%= account_events_url(format: 'json') %>", $('#events'), {bugHeader: true});
  };
}

app/views/projects/show.js.erb
// Copyright 2014 Square Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

$(document).ready(function() { new PageManager().setup(); });

function PageManager() {
  this.setup = function() {
    this.resetClickBinds();
    this.setupSendsEmailsCheckboxes();

    new MemberPanel($('#members'),
                    "<%= escape_javascript @project.name %>",
                    "<%= @project.to_param %>",
                    "<%= users_url %>",
                    "<%= project_memberships_url(@project, format: 'json') %>",
                    "<%= project_membership_url(@project, 'USERID', format: 'json') %>",
                    "<%= project_url(@project, format: 'json') %>",
                    "<%= current_user.role(@project).to_s %>",
                    window.location.hash == '#change_owner');
  };

  this.setupSendsEmailsCheckboxes = function() {
    $('.environment form').each(function(_, formElement) {
      var form = new SmartForm($(formElement), function() {});
      $(formElement).find('input[type=checkbox]').click(function() { form.submit(); });
    });
  };

  this.resetClickBinds = function() {
    var self = this;
    $('a.make-default').click(function(e) {
      $.ajax("<%= project_url @project, format: 'json' %>", {
        type: 'PATCH',
        data: $.param({
                        'project[default_environment_id]': $(e.currentTarget).data('id'),
                        '<%= request_forgery_protection_token %>': '<%= form_authenticity_token %>'
                      }),
        success: function() {
          // change Default to Make Default
          var parent = $('#default-indicator').parent();
          var id = $('#default-indicator').data('id');
          parent.empty();
          $('<a/>').text('Make default').attr({href: '#', 'data-id': id}).addClass('make-default').appendTo(parent);

          // change Make Default to Default
          parent = $(e.currentTarget).parent();
          id = $(e.currentTarget).data('id');
          parent.empty();
          $('<strong/>').text("Default").attr({'data-id': id, id: 'default-indicator'}).appendTo(parent);

          self.resetClickBinds();
        },
        error: function() { new Flash('alert').text("An error occurred when setting the default environment."); }
      });
    });
  };
}